### PR TITLE
Publish November releases

### PR DESCRIPTION
**Pull request by jmudge**

### CODE REVIEW

**Review by jpradocueva — COMMENTED** [review]
We need to discuss the publication of Location and Connectivity Statistics

**Comment by jpradocueva** [comment]
I see that the Location version is v1.0.3 and Connectivity Statistics 1.0.5.
If we don't have the third digit is confusing, but going forward is not right to have the third digit ...

image

**Comment by jmudge** [comment]
@jpradocueva the versions in index.html were ratified by the Board.

**Review by seanmcilroy29 — APPROVED** [review]
Good to go, notwithstanding Joaquin's third digit comment.

**Comment by jpradocueva** [comment]
@jmudge @seanmcilroy29 we can go ahead with the merge. DMSE agreed to keep the three digits for the enabler but not for the objects. I wonder if we could do something similar for the release tag in the "objects-lwm2m" repo. But at the moment, we can merge this content. DMSE will discuss how to resolve the release tags in "objects-lwm2m"

**Pull request merged**
